//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gFitness.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gFitnessEntities : DbContext
    {
        public gFitnessEntities()
            : base("name=gFitnessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FitnessClubOwners> FitnessClubOwners { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Trainers> Trainers { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserDetails> UserDetails { get; set; }
    }
}
