//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gFitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public int MemberId { get; set; }
        public string IdentityNumber { get; set; }
        public string Gender { get; set; }
        public string Adress { get; set; }
        public string BirthDate { get; set; }
        public int UserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
